meta_product_name: "Journée de l'enseignement supérieur Edition 2022"
meta_title: "L’Agence Erasmus+ France / Education Formation organise les 5 et 6 juillet, à Bordeaux et en ligne, ses journées Erasmus+ Enseignement supérieur."
meta_description: "Elles s’adressent à l’ensemble des établissements d’enseignement supérieur français : universités, écoles, instituts, filières BTS, CFA du supérieur, ...Ces journées aborderont les 4 priorités du programme Erasmus + 2021-2027 :
- Inclusion et diversité,
- Transition écologique,
- Transition numérique,
- Education et engagement citoyen
Comment les établissements se saisissent des opportunités Erasmus+ pour renforcer leurs stratégies sur ces 4 sujets ?"
meta_image: "accueil-banner.png" # should exist in `app/assets/images/`
twitter_account: "@ErasmusplusFR"   # required for Twitter Cards
