meta_product_name: "Inauguration Agence Aquilogia Saint-Jean-de-Luz"
meta_title: "Inauguration Agence Aquilogia Saint-Jean-de-Luz"
meta_description: "Inauguration Agence Aquilogia Saint-Jean-de-Luz"
meta_image: "aquilogia_banner.png" # should exist in `app/assets/images/`
# twitter_account: "@ErasmusplusFR"   # required for Twitter Cards
