meta_product_name: "Webconférence Orientation et compétences à l'ère des transitions"
meta_title: "Webconférence Orientation et compétences à l'ère des transitions"
meta_description: "Placée sous le signe de l’Année européenne des compétences par la Commission européenne, l’année 2023 ambitionne de donner un nouvel élan à l’apprentissage tout au long de la vie. En cette période de transition écologique, numérique et d’évolution du marché du travail, comment accompagner les citoyens dans l'acquisition de compétences adaptées ?"
meta_image: "accueil-banner.png" # should exist in `app/assets/images/`
# twitter_account: "@ErasmusplusFR"   # required for Twitter Cards
