meta_product_name: "Les Jeudis du Littoral Ouest Africain"
meta_title: "Les Jeudis du Littoral Ouest Africain - Série de téléconférences"
meta_description: "L’Université Assane Seck de Ziguinchor (UASZ) et le Grdr Migration-Citoyenneté-Développement ont le plaisir de vous inviter à un cycle de conférences en ligne qui se tiendront les jeudis 10, 17 et 24 juin 2021, de 9h à 10h30 GMT (11h à 12h30 heure française) !"
meta_image: "banniere_grdr_reseaux.png" # should exist in `app/assets/images/`
twitter_account: "@GRDR1"   # required for Twitter Cards
