meta_product_name: "Webcast Reconnaissance de la mobilité européenne en Formation professionnelle Initiale"
meta_title: "Webcast Reconnaissance de la mobilité européenne en Formation professionnelle Initiale"
meta_description: "Outils et dispositifs liés à la valorisation et la reconnaissance des acquis d’apprentissage lors d’une mobilité européenne/internationale des apprenants de l’enseignement et la formation professionnels."
meta_image: "accueil-banner.png" # should exist in `app/assets/images/`
# twitter_account: "@ErasmusplusFR"   # required for Twitter Cards
